# Generated by Django 3.2 on 2022-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
