# Generated by Django 4.0.2 on 2022-07-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectdetails_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
