# Generated by Django 4.0.2 on 2023-06-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_user_date_visited_user_visitdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
