# Generated by Django 4.0.2 on 2023-06-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
