# Generated by Django 4.0.2 on 2023-06-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_monitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitor',
        ),
    ]
